services:
  keep-frontend:
    extends:
      file: docker-compose.common.yml
      service: keep-frontend-common
    image: us-central1-docker.pkg.dev/keephq/keep/keep-ui
    environment:
      - AUTH_TYPE=KEYCLOAK
      - KEYCLOAK_ID=keep
      - KEYCLOAK_ISSUER=http://${KEYCLOAK_HOST:-localhost}:8181/auth/realms/keep
      - KEYCLOAK_SECRET=keep-keycloak-secret
      - API_URL=http://keep-backend:8080
    volumes:
      - ./state:/state
    depends_on:
      - keep-backend

  keep-backend:
    extends:
      file: docker-compose.common.yml
      service: keep-backend-common
    image: keep-api
    build:
      context: .
      dockerfile: ./docker/Dockerfile.api
    environment:
      - AUTH_TYPE=KEYCLOAK
      - KEYCLOAK_URL=http://${KEYCLOAK_HOST:-localhost}:8181/auth
      - KEYCLOAK_REALM=keep
      - KEYCLOAK_CLIENT_ID=keep
      - KEYCLOAK_CLIENT_SECRET=keep-keycloak-secret
      - KEYCLOAK_ADMIN_USER=keep_admin
      - KEYCLOAK_ADMIN_PASSWORD=keep_admin
      - KEYCLOAK_AUDIENCE=realm-management
      - PROMETHEUS_MULTIPROC_DIR=/tmp/prometheus
      - SECRET_MANAGER_TYPE=FILE
      - KEEP_METRICS=true
    volumes:
      - ./state:/state

  keep-websocket-server:
    extends:
      file: docker-compose.common.yml
      service: keep-websocket-server-common

  grafana:
    image: grafana/grafana:latest
    profiles:
      - grafana
    ports:
      - "3001:3000"
    volumes:
      - ./grafana:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/etc/grafana/dashboards
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    depends_on:
      - prometheus

  prometheus:
    image: prom/prometheus:latest
    profiles:
      - grafana
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    depends_on:
      - keep-backend
